// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QBPomAZ4KHaA1XowCAhGlwai7jNPS3s',
    appId: '1:617595452904:web:09891117b401a8f573b85d',
    messagingSenderId: '617595452904',
    projectId: 'reddit-clone-33d80',
    authDomain: 'reddit-clone-33d80.firebaseapp.com',
    storageBucket: 'reddit-clone-33d80.firebasestorage.app',
    measurementId: 'G-WMVXTSSMC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkUOnQkH5ctKbqh7G214pezFrJ2NxYwY',
    appId: '1:617595452904:android:a3388e4d7b868b6f73b85d',
    messagingSenderId: '617595452904',
    projectId: 'reddit-clone-33d80',
    storageBucket: 'reddit-clone-33d80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATx7f-fBB1jrepX7ONVKn5TosDk2awPAo',
    appId: '1:617595452904:ios:bdb355414553db6b73b85d',
    messagingSenderId: '617595452904',
    projectId: 'reddit-clone-33d80',
    storageBucket: 'reddit-clone-33d80.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATx7f-fBB1jrepX7ONVKn5TosDk2awPAo',
    appId: '1:617595452904:ios:bdb355414553db6b73b85d',
    messagingSenderId: '617595452904',
    projectId: 'reddit-clone-33d80',
    storageBucket: 'reddit-clone-33d80.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QBPomAZ4KHaA1XowCAhGlwai7jNPS3s',
    appId: '1:617595452904:web:c9e49b4fd9ed002173b85d',
    messagingSenderId: '617595452904',
    projectId: 'reddit-clone-33d80',
    authDomain: 'reddit-clone-33d80.firebaseapp.com',
    storageBucket: 'reddit-clone-33d80.firebasestorage.app',
    measurementId: 'G-YBF6DXBEMH',
  );
}
